MvcAdminTemplate/Models/Teacher.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace Studenter.Models
{
    public class Teacher : Person
    {
        public virtual ICollection<Group> Groups { get; set; }
    }
}

MvcAdminTemplate/Controllers/EntityControllers/TeacherController.cs
using Studenter.Binders;
using Studenter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Studenter.Controllers.EntityControllers
{
    public class TeacherController : EntityController<Teacher>
    {
        public override ActionResult Update(string id)
        {
            var teacher = App<Teacher>.Managers.Teacher.Get(id);
            return View(teacher);
        }

        public override ActionResult Update([ModelBinder(typeof(TeacherModelBinder))]Teacher entity)
        {
            return base.Update(entity);
        }
    }
}

MvcAdminTemplate/Views/Teacher/Create.cshtml
@model Studenter.Models.Teacher

@{
    ViewBag.Title = "Новый преподаватель";
}

<div class="col-md-10">
    <div class="row">
        <div class="panel panel-default bootstrap-admin-no-table-panel">
            <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">Преподаватель</div>
            </div>
            <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
                @using (Html.BeginForm("Create", "Teacher", FormMethod.Post, new { @class = "form-horizontal" }))
                { 
                    <fieldset>
                        <legend>Создание преподавателя</legend>
                        <div class="form-group">
                            @Html.LabelFor(x => x.FirstName, htmlAttributes: new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.FirstName, htmlAttributes: new { @clas = "form-control" })
                            </div>
                        </div>
                        <div class="form-group">
                            @Html.LabelFor(x => x.SecondName, htmlAttributes: new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.SecondName, htmlAttributes: new { @clas = "form-control" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="reset" class="btn btn-default">Очистить</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>

MvcAdminTemplate/Views/Teacher/List.cshtml
@model  List<Studenter.Models.Teacher>

@{
    ViewBag.Title = "Список студентов";
}

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="text-muted bootstrap-admin-box-title"><a href="@Url.Action("Create", "Teacher")">+ Добавить преподавателя</a></div>
        </div>
        <div class="bootstrap-admin-panel-content">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Имя</th>
                        <th>Фамилия</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var student in Model.OrderBy(x => x.Name))
                    {
                        <tr>
                            <td>@student.FirstName</td>
                            <td>@student.SecondName</td>
                        </tr>
                    }                    
                </tbody>
            </table>
        </div>
    </div>
</div>

MvcAdminTemplate/Views/Teacher/Update.cshtml
@model Studenter.Models.Teacher

@{
    ViewBag.Title = "Редактирование преподавателя";
    var groups = Studenter.App<Studenter.Models.Group>.BaseManager.GetEntities();
}

<div class="col-md-10">
    <div class="row">
        <div class="panel panel-default bootstrap-admin-no-table-panel">
            <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">Преподаватель</div>
            </div>
            <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
                @using (Html.BeginForm("Update", "Teacher", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        <legend>Редактирование преподавателя</legend>
                        <div class="row">
                            <div class="col-md-5">

                                <div class="form-group">
                                    @Html.LabelFor(x => x.FirstName, htmlAttributes: new { @class = "col-lg-2 control-label" })
                                    <div class="col-lg-10">
                                        @Html.TextBoxFor(x => x.FirstName, htmlAttributes: new { @clas = "form-control" })
                                    </div>
                                </div>
                                <div class="form-group">
                                    @Html.LabelFor(x => x.SecondName, htmlAttributes: new { @class = "col-lg-2 control-label" })
                                    <div class="col-lg-10">
                                        @Html.TextBoxFor(x => x.SecondName, htmlAttributes: new { @clas = "form-control" })
                                    </div>
                                </div>
                            </div>
                            <div class="col-md-7">

                                @Html.ListBoxFor(x => x.Groups,
                            new List<SelectListItem>(
                                    Model.Groups.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id })), new { @class = "select-to", multiple = "multiple", size = 5 })


                                
                                <a href="JavaScript:void(0);" id="btn-remove">Удалить &raquo;</a>
                                <a href="JavaScript:void(0);" id="btn-add">&laquo; Добавить</a>
                             

                                @Html.DropDownList("allGroups",
                            new List<SelectListItem>(
                                    groups.Select(x => new SelectListItem() { Text = x.Name, Value = x.Id })), new { @class = "select-from", multiple = "multiple", size = 5 })

                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="reset" class="btn btn-default">Очистить</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>

@section Scripts
{
    <script type="text/javascript">
        $(document).ready(function () {

            $('#btn-add').click(function () {
                $('.select-from option:selected').each(function () {
                    $('.select-to').append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
                    $(this).remove();
                });
            });
            $('#btn-remove').click(function () {
                $('.select-to option:selected').each(function () {
                    $('.select-from').append("<option value='" + $(this).val() + "'>" + $(this).text() + "</option>");
                    $(this).remove();
                });
            });

        });
    </script>
}