MvcAdminTemplate/Models/Group.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace Studenter.Models
{
    public class Group : BaseEntity
    {
        [Display(Name = "Название группы")]
        public string Name { get; set; }

        public virtual ICollection<Student> Students { get; set; }

        public virtual ICollection<Teacher> Teachers { get; set; }

        public override string ToString()
        {
            return string.Format("{0}-{1}", Id, Name);
        }

        public Group()
        {
            Students = new List<Student>();
        }
    }
}

MvcAdminTemplate/Controllers/EntityControllers/GroupController.cs
using Studenter.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Studenter.Controllers.EntityControllers
{
    public class GroupController : EntityController<Group>
    {
       
    }
}

MvcAdminTemplate/Views/Group/Create.cshtml
@model Studenter.Models.Group

@{
    ViewBag.Title = "Новая группа";
}

<div class="col-md-10">
    <div class="row">
        <div class="panel panel-default bootstrap-admin-no-table-panel">
            <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">Группа</div>
            </div>
            <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
                @using (Html.BeginForm("Create", "Group", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        <legend>Создание группы</legend>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Name, htmlAttributes: new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.Name, htmlAttributes: new { @clas = "form-control" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="reset" class="btn btn-default">Очистить</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>

MvcAdminTemplate/Views/Group/List.cshtml
@model  List<Studenter.Models.Group>

@{
    ViewBag.Title = "Список груп";
}

<div class="row">
    <div class="panel panel-default">
        <div class="panel-heading">
            <div class="text-muted bootstrap-admin-box-title"><a href="@Url.Action("Create", "Group")">+ Добавить группу</a></div>
        </div>
        <div class="bootstrap-admin-panel-content">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Название группы</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var student in Model.OrderBy(x => x.Name))
                    {
                        <tr>
                            <td>@student.Name</td>
                        </tr>
                    }                    
                </tbody>
            </table>
        </div>
    </div>
</div>

MvcAdminTemplate/Views/Group/Update.cshtml
@model Studenter.Models.Group

@{
    ViewBag.Title = "Редактирование групы";
}

<div class="col-md-10">
    <div class="row">
        <div class="panel panel-default bootstrap-admin-no-table-panel">
            <div class="panel-heading">
                <div class="text-muted bootstrap-admin-box-title">Группа</div>
            </div>
            <div class="bootstrap-admin-no-table-panel-content bootstrap-admin-panel-content collapse in">
                @using (Html.BeginForm("Update", "Group", FormMethod.Post, new { @class = "form-horizontal" }))
                {
                    <fieldset>
                        <legend>Создание группы</legend>
                        <div class="form-group">
                            @Html.LabelFor(x => x.Name, htmlAttributes: new { @class = "col-lg-2 control-label" })
                            <div class="col-lg-10">
                                @Html.TextBoxFor(x => x.Name, htmlAttributes: new { @clas = "form-control" })
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Сохранить</button>
                        <button type="reset" class="btn btn-default">Очистить</button>
                    </fieldset>
                }
            </div>
        </div>
    </div>
</div>